### ISSUE TITLE
 Set min/max range

### ISSUE THREAD

**Issue by gonzou3d** [p2or/blender-shapekey-extras#2]
Hello poor,

It's been a while :).
I use your add-on quite often and found a way to improve it even further (if you'll find some time, please consider it).
I've found, that sometimes I need to change the Min or Max RANGE for the multiple shape keys. When I have about 300 shapekeys and want to change the RANGE for all of them separately it is a real pain.
Could you improve your add-on, so I may set the Min/Max RANGE value for multiple/random shape keys?

Thanks in advance for your help.
Paul

**Comment by p2or** [comment]
Hey Paul,

I've added this feature to the new release: https://github.com/p2or/blender-shapekeyextras/releases/tag/0.0.7. Set the range via existing _Min/Max sliders_ and simply press _Set Shape Key Range_.

I hope you like it.

**Comment by gonzou3d** [comment]
Hello,

Your new feature works fantastic. It is a really time saver for me. Thanks :D !
I am happy you've released the .py file I can easily instal.

P.s. I noticed, that after installing your add-on, there is a **+** sign in the _Exclude Only_ window.
Could you remove it, so after enabling the add-on this window will be blank?

Thanks for keeping up the good work!
