### ISSUE TITLE
Creating the numerical list for the shapekeys

### ISSUE THREAD

**Issue by gonzou3d** [p2or/blender-shapekey-extras#6]
I wonder if this is possible to assign the numbers to the shapekeys creating the numerical list via scripting as pictured below? It may help to keep things more organized and clean.
![shapekeys numerical list](https://user-images.githubusercontent.com/16025201/29876982-98030a36-8d9e-11e7-9ba5-97600fb6f2e5.png)

**Comment by p2or** [comment]
Hey Paul, 

I've implemented that in Version 0.1.8, although in a *very hacky* way. If you notice some strange behavior, please report it here.

Cheers,
Christian

**Comment by gonzou3d** [comment]
Hey,


Brilliant! Works perfect.

I have a question:
Can you tell me how the licence of your shape keys extras add on works?
E.g. If I would like to sell my customisable model in future can I bundle
your add on to my .blend file (and give a credit to you as an author there)?
Or do I have to give the clients a downloadable link to your add on?
How does it work?

P.s. Actually I plan to sell a customisable jaw model on Blender Market,
which needs only your *Merge Vertex Groups *option (not the entire add on).
Could you send me the code for this one and can I use it in my product?



Thanks,
Paul



2017-08-30 21:02 GMT+02:00 poor <notifications@github.com>:
