### ISSUE TITLE
Moving shape keys up and down on the list by the defined number

### ISSUE THREAD

**Issue by gonzou3d** [p2or/blender-shapekey-extras#7]
Is it possible to create the panel, where you can define the position of selected shape key as pictured below? You select the shapekey, input the number of positions on the list you want to skip and choose the direction. It's time consuming process to put e.g. the shape key which is in the middle of the list on top when you have over 300 of them (you have to click the 'up/down arrow' button again and again or use a _Shift+R_ shortcut). BTW I asked related answer on BSE some time ago: https://blender.stackexchange.com/questions/22994/how-to-manage-the-shapekeys-position-faster
![moving shape keys](https://user-images.githubusercontent.com/16025201/29878329-878c15fe-8da2-11e7-9316-e6512f232688.png)

**Comment by p2or** [comment]
Yep, implemented that. Since Version 0.1.8 you can click on *Shape Key Specials > Move Shape Key*, which allows to set a certain amount to move up or down the list:

![](https://i.stack.imgur.com/DakQZ.jpg)

I hope that's what you want.
Cheers,
Christian
