### ISSUE TITLE
4.1 support

### ISSUE THREAD

**Issue by loicbramoulle** [p2or/blender-shapekey-extras#9]
Hi, really amazing addon, wanted to use it now to set min max values of all my facial mocap shapeskeys, but the addon doesn't seem to support blender 4.1.
Thanks !

**Comment by loicbramoulle** [comment]
Ah my bad the extra menus does seem to appear, I had a crash but it seems to work.
Thanks !

**Comment by p2or** [comment]
Hi @loicbramoulle,

the UI definitely needs some love and I will take care of it when I find some time, but otherwise it still works on my end. Can you confirm?

Cheers,
Christian

**Comment by loicbramoulle** [comment]
Yes I think the menu was folded by default in 4.1 and I first thought it was missing, but when looking in 4.0 I realized it had to be opened/unfolded.
It worked perfectly to set min/max values to my 70 shapes at once !
Thanks !!
